name: ceticy
description: An app to help you manage your meals with your friends.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^1.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

# splash screen configuration
flutter_native_splash:
  color: "#000000"
  image: assets/images/logo-512.png
  android: true
  ios: true
  image_fit: "fill"
