name: Android Release Build
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-android:
    name: 🤖 Build Android Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - run: flutter pub get

      - name: Set Java 17 environment
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adoptopenjdk'

      - run: flutter build apk --release

      - run: flutter build appbundle --release

      - name: Extract version from pubspec.yaml
        run: |
          VERSION=$(grep 'version: ' pubspec.yaml | cut -d ' ' -f2)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Version extracted: $VERSION"

      - name: Fetch tags and check if the tag exists
        run: |
            git fetch --tags
            TAG="v${{ env.VERSION }}"
            if git rev-parse "$TAG" >/dev/null 2>&1; then
              echo "Tag $TAG already exists."
            else
              echo "Tag $TAG does not exist, creating and pushing it."
              git tag "$TAG"
              git push origin "$TAG"
            fi

      - name: Upload APK to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/app/outputs/flutter-apk/app-release.apk
          tag_name: v${{ env.VERSION }}
          overwrite: true
          body: "🚀 APK ${{ env.VERSION }}"
          name: Ceticy-v${{ env.VERSION }}.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Upload AAB to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/app/outputs/bundle/release/app-release.aab
          tag_name: v${{ env.VERSION }}
          overwrite: true
          body: "🚀 AAB ${{ env.VERSION }}"
          name: Ceticy-v${{ env.VERSION }}.aab
          asset_content_type: application/octet-stream