name: Release Build (Android & iOS)
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-android:
    name: 🤖 Build Android Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            .flutter-plugins
            .flutter-plugins-dependencies
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - run: flutter pub get

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set Java 21 environment
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set JAVA_HOME for Gradle
        run: |
          echo "JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV

      - name: Build APK
        run: flutter build apk --release

      - name: Build AAB
        run: flutter build appbundle --release

      - name: Extract version from pubspec.yaml
        run: |
          VERSION=$(grep 'version: ' pubspec.yaml | cut -d ' ' -f2)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Fetch tags and check if the tag exists
        run: |
          git fetch --tags
          TAG="v${{ env.VERSION }}"
          if ! git rev-parse "$TAG" >/dev/null 2>&1; then
            git tag "$TAG"
            git push origin "$TAG"
          fi

      - name: Upload APK to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/app/outputs/flutter-apk/app-release.apk
          tag: v${{ env.VERSION }}
          overwrite: true
          asset_name: Ceticy-v${{ env.VERSION }}.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Upload AAB to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/app/outputs/bundle/release/app-release.aab
          tag: v${{ env.VERSION }}
          overwrite: true
          asset_name: Ceticy-v${{ env.VERSION }}.aab
          asset_content_type: application/octet-stream

  build-ios:
    name: 🎉 Build iOS Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            .flutter-plugins
            .flutter-plugins-dependencies
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - run: flutter pub get

      - name: Build iOS app
        run: flutter build ios --release --no-codesign

      - run: |
          cd build/ios/iphoneos
          mkdir -p Payload
          mv Runner.app Payload/
          zip -r9 CeticyIpaExport.ipa Payload
        working-directory: .

      - name: Extract version from pubspec.yaml
        run: |
          VERSION=$(grep 'version: ' pubspec.yaml | cut -d ' ' -f2)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Fetch tags and check if the tag exists
        run: |
            git fetch --tags
            TAG="v${{ env.VERSION }}"
            if ! git rev-parse "$TAG" >/dev/null 2>&1; then
              git tag "$TAG"
              git push origin "$TAG"
            fi

      - name: Upload IPA to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/CeticyIpaExport.ipa
          tag_name: v${{ env.VERSION }}
          overwrite: true
          name: Ceticy-v${{ env.VERSION }}.ipa
          asset_content_type: application/octet-stream
